### PR TITLE
feat: add shareable link

### PR DESCRIPTION
**Pull request by IgboPharaoh**
This PR adds a shareable link to the address bar of the browser to enable users to share a link to their last search query

### CODE REVIEW

**Comment by adamjonas** [comment]
ACK on functionality

**Comment by adamjonas** [comment]
@Emmanuel-Develops or @Extheoisah can you take a look at the code?

**Comment by Extheoisah** [comment]
There's a bug with the useEffect. I think the dependency on userInput causes the unnecessary re-renders
https://www.loom.com/share/ced9c84a3a1146788d232b9a15b6e343?sid=bf0015cd-172d-4684-9afc-90b3f1f338b4

**Review by Extheoisah — CHANGES_REQUESTED** [review]
A couple of things to fix: 
- After the chat response has been generated and you enter a new input, we get the author introductory text every time. 

- The url only updates after the query response is generated. I'm not sure that's what we want. we want the query to be populated once the query has been sent regardless of the response.

see video here -> https://www.loom.com/share/1423d7c655674bf7b6f6dd73320389aa?sid=4a2c0f8f-ef61-4335-81f1-90a4c9a7c5ce

**Comment by IgboPharaoh** [comment]
let me look into these

**Review by Extheoisah — APPROVED** [review]

**Comment by Extheoisah** [comment]
All good!
A follow up pr (nice to have) would be being able to copy/share the link for a specific question/response.

**Comment by IgboPharaoh** [comment]
Will put that into consideration

**Pull request merged**
